const CAP={volunteers:6,generators:1,rooms:1};
const DEF={delivery:['Prepare tomorrow supplies','Food court',1,{volunteers:2},20,2],power:['Stage power failure','Main stage',10,{volunteers:2,generators:1},80,8],rain:['Rain approaching','Indoor hall',8,{volunteers:3,generators:1,rooms:1},60,2],crowd:['Entrance queue growing','Entrance',7,{volunteers:4},30,2]};
export function createBrowserDemo(){
 let s,run=1;
 const log=(type,message,id=null)=>s.events.unshift({sequence:s.events.length+1,timestamp:new Date().toISOString(),type,message,loop_id:id,payload:{}});
 const reset=()=>{s={run_id:run++,status:'ready',tick:0,active:null,incidents:[],events:[],resources:{...CAP},capacity:CAP,budget:300,metrics:{resolved:0,switches:0,rejected:0,recovered:0},decision:null,mode:'demo',busy:false,connection:{signed_in:false,message:'Codex mode requires the local backend.'}};add('delivery');log('welcome','Festival ready. Start the exercise, then add an incident.');};
 function add(kind){if(!DEF[kind]||s.incidents.some(i=>i.kind===kind&&!['resolved','stopped'].includes(i.status)))throw Error('This incident is already active.');const [title,zone,priority,needs,cost,work]=DEF[kind],id='incident-'+(s.incidents.length+1);s.incidents.push({id,kind,title,zone,priority,description:'Coordinate this simulated festival incident.',needs:{...needs},cost,status:'queued',stage:'plan',age:0,attempts:0,plan:null,checkpoint:null,allocation:{},work_left:work,error:'',fingerprints:[],history:[],announcement:'',blocked_by:[]});log('arrival',title+' added with priority '+priority+'.',id);}
 const release=i=>{for(const [k,v] of Object.entries(i.allocation))s.resources[k]+=v;i.allocation={};};
 function turn(){s.tick++;const a=s.incidents.filter(i=>!['resolved','stopped'].includes(i.status));a.forEach(i=>i.age++);const q=a.filter(i=>i.status!=='blocked'||Object.entries(i.needs).every(([k,v])=>s.resources[k]>=v));if(!q.length){s.status=a.length?'waiting':'completed';return;}q.sort((x,y)=>(y.priority+Math.floor(y.age/3))-(x.priority+Math.floor(x.age/3))||y.age-x.age);const i=q[0],bonus=Math.floor(i.age/3);s.decision={selected:i.id,cycle:s.tick,candidates:q.map(x=>({title:x.title,base:x.priority,age_bonus:Math.floor(x.age/3),score:x.priority+Math.floor(x.age/3)}))};log('schedule',i.title+' selected: base '+i.priority+' + waiting bonus '+bonus+' = '+(i.priority+bonus)+'.',i.id);i.age=0;
 if(i.stage==='plan'){i.plan={summary:'Coordinate a response to '+i.title.toLowerCase()+'.',resources:{...i.needs},cost:i.cost,steps:['Assign the response team.','Set up required resources.','Confirm the area is ready.'],announcement:'Festival update: the team is addressing '+i.title.toLowerCase()+'. Follow volunteer directions.'};i.checkpoint=structuredClone(i.plan);i.stage='reserve';log('checkpoint','Demo plan checked. Checkpoint saved; resources are not yet reserved.',i.id);}
 else if(i.stage==='reserve'){if(!Object.entries(i.plan.resources).every(([k,v])=>v<=s.resources[k])){i.status='blocked';i.blocked_by=s.incidents.filter(x=>x.id!==i.id&&Object.values(x.allocation).some(v=>v>0)).map(x=>x.id);log('waiting','Waiting for required resources.',i.id);return;}i.allocation={...i.plan.resources};for(const[k,v]of Object.entries(i.allocation))s.resources[k]-=v;s.budget-=i.plan.cost;i.status='responding';i.stage='respond';log('reserved','All required resources reserved together.',i.id);}
 else if(i.stage==='respond'){if(--i.work_left<=0){i.stage='announce';log('checked','Response finished; ready to publish the visitor notice.',i.id);}else log('working','Response team is implementing the checked plan.',i.id);}
 else{i.announcement=i.plan.announcement;i.status='resolved';release(i);s.metrics.resolved++;log('resolved','Incident resolved in the simulation. Resources released; visitor notice published.',i.id);}}
 reset();
 return{async get(){if(s.status==='running')turn();return structuredClone(s);},async post(path,value){if(path==='control/start'){s.status='running';log('start','Exercise started.');}else if(path==='control/pause'){s.status='paused';log('pause','Pause requested at a safe step boundary.');}else if(path==='control/step'){if(s.status==='running')throw Error('Pause before stepping manually.');turn();}else if(path==='control/reset')reset();else if(path==='incidents')add(value);else if(path.startsWith('incidents/')&&path.endsWith('/stop')){const i=s.incidents.find(x=>x.id===path.split('/')[1]);if(!i)throw Error('Unknown incident');release(i);i.status='stopped';i.error='Stopped by operator. Reserved resources released.';log('stopped',i.error,i.id);}else throw Error('Codex mode requires the local FastAPI backend.');return structuredClone(s);}};
}
